movieapp/urls.py
from . import views
from django.urls import path

app_name = 'movieapp'
urlpatterns = [

    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id2>/', views.update, name='update'),
    path('delete/<int:id1>/', views.delete, name='delete'),
]

movieproject/urls.py
from movieproject import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='picture')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

movieapp/views.py
from django.shortcuts import render, redirect

from movieapp.forms import MovieForm
from movieapp.models import Movie


# Create your views here.
def index(request):
    movie = Movie.objects.all()

    return render(request, "index.html", {'movie_list': movie})


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "detail.html", {'movie1': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
        return redirect('/')
    return render(request, "add.html")


def update(request, id2):
    movie = Movie.objects.get(id=id2)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, "edit.html", {'form': form, 'movie': movie})


def delete(request, id1):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id1)
        movie.delete()
        return redirect('/')
    return render(request, "delete.html")

templates/add.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
        <br>
        <label><h3>Add New Movie</h3></label><br><br>
      <input type="text" name="name" placeholder="Enter Movie Name" required><br><br>
      <input type="text" name="desc" placeholder="Enter Movie description"><br><br>
      <input type="text" name="year" placeholder="Enter Movie year"><br><br>
      <input type="file" name="img"><br><br>
      <input type="submit">
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'movieapp:index' %}">
<!--    <img src="" width="30" height="30" class="d-inline-block align-top" alt="">-->
    Online Movie Store

  </a>
    <a class="navbar-brand" href="{% url 'movieapp:add_movie' %}">Add Movie</a>
    <a class="navbar-brand" href="#">About Us</a>
    <a class="navbar-brand" href="#">Contact Us</a>
    <a class="navbar-brand" href="#">Help</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
  {% csrf_token %}
  <h3>Are you sure you want to delete this movie?</h3><br><br>
  <input type="submit">
  <button type="reset">Cancel</button>
</form>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row"  style="margin-top: 25px;">
        <div class="col-md-6">
            <img src="{{movie1.img.url}}" width="400px" height="300px">
        </div>
        <div class="col-md-6">
           <h4>{{movie1.name}}</h4><br><br>
           <h5>{{movie1.desc}}</h5><br><br>
           <h5>{{movie1.year}}</h5><br><br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie1.id %}">Update </a>
            <a class="btn btn-danger"  href="{% url 'movieapp:delete' movie1.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <br>
                <h2>Update the Movie</h2><br><br>
            {{form.as_p}}<br>
            <input type="submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 17rem;padding:10px;margin-top: 25px;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100" height="250">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p class="card-text">{{i.year}}</p>
                        <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View Movie Details</a>
                    </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}